# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 06:37
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_planner',
            field=models.BooleanField(default=False, verbose_name='planner'),
        ),
    ]
