# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170122_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_planner',
        ),
    ]
