# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_is_planner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_planner',
            field=models.BooleanField(default=False, verbose_name='planner'),
        ),
    ]
