# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170122_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_planner',
            field=models.BooleanField(default=False, verbose_name='is planner'),
        ),
    ]
