# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_sponsor',
        ),
    ]
