# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_is_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invite_complete', models.BooleanField(default=False)),
                ('invite_code', models.CharField(max_length=50, null=True)),
                ('invite_num_tables', models.IntegerField(default=1)),
            ],
        ),
    ]
