# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170204_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='complete',
            new_name='is_complete',
        ),
    ]
