# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20170204_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
