# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_invite_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='gala_id',
            field=models.IntegerField(null=True),
        ),
    ]
