# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170204_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='gala_id',
        ),
    ]
