# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_invite_gala_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
