# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_complete', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50, null=True)),
                ('table_size', models.IntegerField(default=1)),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
