# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gala_name', models.CharField(max_length=100, verbose_name='event name')),
                ('gala_datetime', models.DateTimeField(verbose_name='event date')),
                ('gala_num_tables', models.IntegerField(default=0, verbose_name='number of tables')),
                ('gala_num_confirmed', models.IntegerField(default=0, verbose_name='number of confirmed guests')),
                ('gala_num_invited', models.IntegerField(default=0, verbose_name='number of invited guests')),
                ('gala_max_guests', models.IntegerField(verbose_name='maximum number of guests allowed')),
                ('gala_has_limit', models.BooleanField(default=False, verbose_name='has maximum')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='MealChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='meal choice')),
                ('num_selected', models.IntegerField(default=0, verbose_name='number of times selected')),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galasetter.Gala')),
            ],
        ),
    ]
