# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galasetter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gala',
            name='gala_datetime',
        ),
        migrations.AddField(
            model_name='gala',
            name='gala_date',
            field=models.DateField(null=True, verbose_name='event date'),
        ),
        migrations.AddField(
            model_name='gala',
            name='gala_time',
            field=models.TimeField(null=True, verbose_name='event time'),
        ),
        migrations.AlterField(
            model_name='gala',
            name='gala_max_guests',
            field=models.IntegerField(default=0, verbose_name='maximum number of guests allowed'),
        ),
    ]
