# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galasetter', '0002_auto_20170124_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gala',
            name='gala_date',
        ),
        migrations.RemoveField(
            model_name='gala',
            name='gala_time',
        ),
        migrations.AddField(
            model_name='gala',
            name='gala_datetime',
            field=models.DateTimeField(null=True, verbose_name='event date'),
        ),
    ]
