# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galasetter', '0006_mealchoice_choice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealchoice',
            name='choice_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='meal description'),
        ),
    ]
