# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galasetter', '0007_auto_20170131_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealchoice',
            old_name='choice_description',
            new_name='choice_desc',
        ),
    ]
