# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='table',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_sponsor',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
