# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0003_auto_20170124_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='gala',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='gala',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date updated'),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='other_comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gala',
            name='gala_name',
            field=models.CharField(max_length=100, verbose_name='event name'),
        ),
        migrations.AlterField(
            model_name='gala',
            name='gala_num_tables',
            field=models.IntegerField(verbose_name='number of tables'),
        ),
        migrations.AlterField(
            model_name='gala',
            name='gala_total_guests',
            field=models.IntegerField(verbose_name='maximum number of guests'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_sponsor',
            field=models.CharField(max_length=150, verbose_name='table sponsor'),
        ),
    ]
