# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 05:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0005_table_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_contact', models.CharField(max_length=150, verbose_name='full name of party contact')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_completed', models.BooleanField(default=False)),
                ('is_donated', models.BooleanField(default=False)),
                ('seat_number', models.IntegerField(verbose_name='seat number')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tablesetter.Party')),
            ],
        ),
        migrations.CreateModel(
            name='SeatDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=50)),
                ('guest_last_name', models.CharField(max_length=50)),
                ('meal_choice', models.CharField(max_length=200, verbose_name='meal choice')),
                ('dietary_restrictions', models.CharField(blank=True, max_length=300, verbose_name='dietary restrictions')),
                ('special_accommodations', models.CharField(blank=True, max_length=300)),
                ('initial_response_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tablesetter.Seat')),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='table',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='table_sponsor',
            new_name='table_sponsor_name',
        ),
        migrations.AlterField(
            model_name='table',
            name='gala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galasetter.Gala'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.DeleteModel(
            name='Gala',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AddField(
            model_name='seat',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesetter.Table'),
        ),
        migrations.AddField(
            model_name='party',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablesetter.Table'),
        ),
    ]
