# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0006_auto_20170124_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='table',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='party',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='seat',
            name='invite_is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='last_invite_sent_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='details_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seatdetails',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='seatdetails',
            name='guest_first_name',
            field=models.CharField(max_length=50, verbose_name="guest's first name"),
        ),
        migrations.AlterField(
            model_name='seatdetails',
            name='guest_last_name',
            field=models.CharField(max_length=50, verbose_name="guest's last name"),
        ),
        migrations.AlterField(
            model_name='seatdetails',
            name='initial_response_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='initial response date'),
        ),
        migrations.AlterField(
            model_name='seatdetails',
            name='meal_choice',
            field=models.CharField(max_length=300, verbose_name='meal choice'),
        ),
        migrations.AlterField(
            model_name='seatdetails',
            name='special_accommodations',
            field=models.CharField(blank=True, max_length=300, verbose_name='special accommodations'),
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
