# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0007_auto_20170126_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='user',
            new_name='table_sponsor',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_sponsor_name',
        ),
    ]
