# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0009_auto_20170131_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='last_invite_sent_datetime',
            new_name='last_invite_sent',
        ),
        migrations.AlterField(
            model_name='table',
            name='table_sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
