# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0010_auto_20170201_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_sponsor',
        ),
        migrations.AddField(
            model_name='table',
            name='sponsor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
