# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0011_auto_20170202_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
