# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0012_auto_20170204_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(default=10, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
