# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesetter', '0013_auto_20170204_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='sponsor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
