# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170204_2229'),
        ('tablesetter', '0014_auto_20170204_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
